### ISSUE TITLE
QNAP QTS Container Station deployment

### ISSUE THREAD

**Issue by szabeszg** [linuxserver/docker-bookstack#214]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The Maria DB's socket on QTS is /var/run/mariadb10.sock and maybe that's why I was unable to make it work. During installation, the database was not found, even though I provided all parameters as environmental variables before deploying the container.

### Reason for change

The benefit would be that the very popular QNAP systems could easily run BookStack.

**Comment by thespad** [comment]
This appears to be a request for support rather than a feature request. If it *is* a feature request please provide actual details of what you're asking for, and if it's a support request please either open a Bug report and complete the template or visit our Discord or Discourse for realtime support.

**Comment by szabeszg** [comment]
I see. I will visit your Discord support then, thanks.
