### ISSUE TITLE
File upload limit set to 2MB

### ISSUE THREAD

**Issue by StevenReitsma** [linuxserver/docker-bookstack#51]
It would be nice if the default upload limit could be increased a bit, as it's currently set to 2MB. It can already be easily changed by adding these lines to `/config/php/php-local.ini`:

```
post_max_size = 10M
upload_max_filesize = 10M
```

However, I think it's sensible to increase the defaults to 10MB, as recommended in the [docs](https://www.bookstackapp.com/docs/admin/upload-config/).

**Comment by d3wy** [comment]
I've spent the last 25 minutes googling around after finding myself unable to upload a 2.5MB files, this limit was a little hard to identify the cause of immediately and this issue specific helped me to resolve it. A slightly larger size would be a good start and maybe calling it out in the documentation?

**Comment by StevenReitsma** [comment]
Not stale, still needs fixing

**Comment by aptalca** [comment]
#63

**Comment by BerndErnst** [comment]
Still need fixing. I was busy for the last 2 hours trying to find the root cause - no sucess.
My error message when uploading is:
"The server does not allow uploads of this size. Please try a smaller file size."
In config/bookstack/php/php-local.ini I checked everything, the syntax, different values. No effect at all. It seems like the config file isn't read. But the files were created from the application and it's mounted correctly.
I also checked the nginx config and the value is set to 0, which means unlimited.
My upload limit is still 1 MB.
I also changed the frontend code but I don't expect the problem to be there since the error message says clearly it's a backend problem.
