### ISSUE TITLE
Instructions in readme are wrong. 

### ISSUE THREAD

**Issue by JC5** [linuxserver/docker-bookstack#56]
The bot already triaged incorrectly closed issue #55 to “done” but I want to stress it’s not fixed. Here are to screenshots. Thanks for your time. 

![E1A99077-FBE5-4108-B310-71753FA2340A](https://user-images.githubusercontent.com/5889984/74086935-04842c00-4a88-11ea-82b8-e8e067567fd0.jpeg)
![94EBA23A-4A64-4FEC-9B4F-BBE3467EF4A2](https://user-images.githubusercontent.com/5889984/74086936-05b55900-4a88-11ea-9472-7c935df96c06.jpeg)

**Comment by thelamer** [comment]
Why are you still opening issues about this @aptalca clearly linked the correct line to explain how we sub in this value https://github.com/linuxserver/docker-bookstack/blob/master/root/etc/cont-init.d/50-config#L56

Have you even tested the container?

**Comment by JC5** [comment]
That’s why opened the issue. Because using DB_USER doesn’t work. And when I click code in the top bar, and go to readme, the instructions insist it has to be DB_USER. Which doesn’t work. Which is why I opened the issue. 

Have you tested the container? Because I have. And it doesn’t work.

**Comment by aptalca** [comment]
If you had filled out the issue template as required, rather than deleting it, you would have had to try the command in the readme to provide the necessary logs. They would either have showed you that the readme is indeed correct, or (as you say you tried it and failed) it would have uncovered a separate issue. But we'll never know since you didn't do that.

We keep closing the issues because you keep insisting that the readme is wrong even after we pointed you to the code that backs up the readme.

**Comment by thelamer** [comment]
This container has 15 million pulls and yes I just tried it works great with the compose example provided.
You keep pinging the main maintainers of these projects insisting they are wrong when you just need user support because you obviously do not know what you are doing, 

You need to rethink your approach to dealing with people online in general, don't assume you know more than everyone all the time and take a moment to politely ask for free help. We have a discord and a discourse , use that for support.

**Comment by CHBMB** [comment]
I've tested the container and it worked for me.....

**Comment by JC5** [comment]
It’s ok. Looks like I was messing up and taking out IRL frustrations out on you guys. I shouldn’t have done that and I sincerely apologize.

**Comment by CHBMB** [comment]
Appreciate the apology. ;)
